## Automatically generated by gen.pl, don't edit #	<remove the line>


#MULTIPVC_SUPPORT	is not set     <remove the line>
# CONFIG_MULTIPVC is not set	<remove the line>
#AUTODETECT_DHCP_SUPPORT	is not set     <remove the line>
# CONFIG_AUTODETECT_DHCP is not set	<remove the line>
#SNMPV3_SUPPORT	is not set     <remove the line>
# CONFIG_SNMPV3 is not set	<remove the line>
#QOS_ADVANCE_SUPPORT	is not set     <remove the line>
# CONFIG_QOS_ADVANCE is not set	<remove the line>
#SAVE_LOG_SUPPORT	is not set     <remove the line>
# CONFIG_SAVE_LOG is not set	<remove the line>
#ADVANCED_FORWARD_SUPPORT	is not set     <remove the line>
# CONFIG_ADVANCED_FORWARD is not set	<remove the line>
#DNSPROXY_BUTTON_SUPPORT	is not set     <remove the line>
# CONFIG_DNSPROXY_BUTTON is not set	<remove the line>
#NOMAD_SUPPORT	is not set     <remove the line>
# CONFIG_NOMAD is not set	<remove the line>
QOS_SUPPORT=1
CONFIG_QOS=y
#QOS_ADVANCED_SUPPORT	is not set     <remove the line>
# CONFIG_QOS_ADVANCED is not set	<remove the line>
#ROUTED_UNLIMIT_SUPPORT	is not set     <remove the line>
# CONFIG_ROUTED_UNLIMIT is not set	<remove the line>
#CLI_SUPPORT	is not set     <remove the line>
# CONFIG_CLI is not set	<remove the line>
#IPCP_NETMASK_SUPPORT	is not set     <remove the line>
# CONFIG_IPCP_NETMASK is not set	<remove the line>
#SETUP_WIZARD_FT_SUPPORT	is not set     <remove the line>
# CONFIG_SETUP_WIZARD_FT is not set	<remove the line>
#SECLAN_SUPPORT	is not set     <remove the line>
# CONFIG_SECLAN is not set	<remove the line>
DSL_MODULA_SEL_SUPPORT=1
CONFIG_DSL_MODULA_SEL=y
# LOG_DSL_MODULA_SEL is not set	<remove the line>
#CPED_TR064_SUPPORT	is not set     <remove the line>
# CONFIG_CPED_TR064 is not set	<remove the line>
#STB_SUPPORT	is not set     <remove the line>
# CONFIG_STB is not set	<remove the line>
DNSMASQ_SUPPORT=1
CONFIG_DNSMASQ=y
# LOG_DNSMASQ is not set	<remove the line>
UDHCPD_SUPPORT=1
CONFIG_UDHCPD=y
UDHCPC_SUPPORT=1
CONFIG_UDHCPC=y
# LOG_DHCPD is not set	<remove the line>
# LOG_DHCPC is not set	<remove the line>
IGMP_PROXY_SUPPORT=1
CONFIG_IGMP_PROXY=y
#GRE_SUPPORT	is not set     <remove the line>
# CONFIG_GRE is not set	<remove the line>
#CLOUD_SUPPORT	is not set     <remove the line>
# CONFIG_CLOUD is not set	<remove the line>
#IP2_IP_SUPPORT	is not set     <remove the line>
# CONFIG_IP2_IP is not set	<remove the line>
#FILTER_WAN_SELECT_SUPPORT	is not set     <remove the line>
# CONFIG_FILTER_WAN_SELECT is not set	<remove the line>
PPPOE_SUPPORT=1
CONFIG_PPPOE=y
# LOG_PPPOE is not set	<remove the line>
#PPTP_SUPPORT	is not set     <remove the line>
# CONFIG_PPTP is not set	<remove the line>
# LOG_PPTP is not set	<remove the line>
PPPD_SUPPORT=1
CONFIG_PPPD=y
# LOG_PPPD is not set	<remove the line>
ZEBRA_SUPPORT=1
CONFIG_ZEBRA=y
# LOG_ZEBRA is not set	<remove the line>
TFTPD_SUPPORT=1
CONFIG_TFTPD=y
# LOG_TFTPD is not set	<remove the line>
DDNS_SUPPORT=1
CONFIG_DDNS=y
# LOG_DDNS is not set	<remove the line>
CRON_SUPPORT=1
CONFIG_CRON=y
# LOG_CRON is not set	<remove the line>
HTTPD_SUPPORT=1
CONFIG_HTTPD=y
GET_POST_SUPPORT=1
CONFIG_GET_POST=y
# LOG_HTTPD is not set	<remove the line>
#CWMP_SUPPORT	is not set     <remove the line>
# CONFIG_CWMP is not set	<remove the line>
# LOG_CWMP is not set	<remove the line>
ANTSEL_SUPPORT=1
CONFIG_ANTSEL=y
# LOG_ANTSEL is not set	<remove the line>
#WL_CALIBRATION_ONBOARD_SUPPORT	is not set     <remove the line>
# CONFIG_WL_CALIBRATION_ONBOARD is not set	<remove the line>
# LOG_WL_CALIBRATION_ONBOARD is not set	<remove the line>
LIBMNG_SUPPORT=1
CONFIG_LIBMNG=y
# LOG_LIBMNG is not set	<remove the line>

ifeq (1,1)
#HSIAB_SUPPORT	is not set     <remove the line>
# CONFIG_HSIAB is not set	<remove the line>
# LOG_HSIAB is not set	<remove the line>
#HEARTBEAT_SUPPORT	is not set     <remove the line>
# CONFIG_HEARTBEAT is not set	<remove the line>
# LOG_HEARTBEAT is not set	<remove the line>
#AOL_SUPPORT	is not set     <remove the line>
# CONFIG_AOL is not set	<remove the line>
SETUP_WIZARD_SUPPORT=1
CONFIG_SETUP_WIZARD=y
#PARENTAL_CONTROL_SUPPORT	is not set     <remove the line>
# CONFIG_PARENTAL_CONTROL is not set	<remove the line>
# LOG_PARENTAL_CONTROL is not set	<remove the line>
#DDM_SUPPORT	is not set     <remove the line>
# CONFIG_DDM is not set	<remove the line>
# LOG_DDM is not set	<remove the line>
NTP_SUPPORT=1
CONFIG_NTP=y
MPPPOE_SUPPORT=1
CONFIG_MPPPOE=y
IPPPOE_SUPPORT=1
CONFIG_IPPPOE=y
#CLIP_SUPPORT	is not set     <remove the line>
# CONFIG_CLIP is not set	<remove the line>
#HTTPS_SUPPORT	is not set     <remove the line>
# CONFIG_HTTPS is not set	<remove the line>
#ARP_TABLE_SUPPORT	is not set     <remove the line>
# CONFIG_ARP_TABLE is not set	<remove the line>
#SPECIAL_FORWARD_SUPPORT	is not set     <remove the line>
# CONFIG_SPECIAL_FORWARD is not set	<remove the line>
BACKUP_RESTORE_SUPPORT=1
CONFIG_BACKUP_RESTORE=y

ifeq (0,1)
#FIREWALL_LEVEL_SUPPORT	is not set     <remove the line>
# CONFIG_FIREWALL_LEVEL is not set	<remove the line>
endif

UPNP_FORWARD_SUPPORT=1
CONFIG_UPNP_FORWARD=y
PORT_TRIGGER_SUPPORT=1
CONFIG_PORT_TRIGGER=y
WRITE_MAC_SUPPORT=1
CONFIG_WRITE_MAC=y
WRITE_SN_SUPPORT=1
CONFIG_WRITE_SN=y
DIAG_SUPPORT=1
CONFIG_DIAG=y
endif

#MULTIUSER_SUPPORT	is not set     <remove the line>
# CONFIG_MULTIUSER is not set	<remove the line>
SINGLEUSER_SUPPORT=1
CONFIG_SINGLEUSER=y
#RIP_EXTEND_SUPPORT	is not set     <remove the line>
# CONFIG_RIP_EXTEND is not set	<remove the line>

ifeq (0,1)
#WL_STA_SUPPORT	is not set     <remove the line>
# CONFIG_WL_STA is not set	<remove the line>
endif

#SYSLOG_SUPPORT	is not set     <remove the line>
# CONFIG_SYSLOG is not set	<remove the line>
#KLOGD_SUPPORT	is not set     <remove the line>
# CONFIG_KLOGD is not set	<remove the line>
#SNMP_SUPPORT	is not set     <remove the line>
# CONFIG_SNMP is not set	<remove the line>
# LOG_SNMP is not set	<remove the line>
#NETMASK_CLASS_SUPPORT	is not set     <remove the line>
# CONFIG_NETMASK_CLASS is not set	<remove the line>
#PPP_DETAIL_STAT_SUPPORT	is not set     <remove the line>
# CONFIG_PPP_DETAIL_STAT is not set	<remove the line>
# EMI_TEST is not set	<remove the line>
# DEBUG_WEB is not set	<remove the line>
# DEBUG_RC is not set	<remove the line>
# BRCM is not set	<remove the line>
# MY_DEBUG is not set	<remove the line>
MULTILANG_SUPPORT=1
CONFIG_MULTILANG=y
# DEBUG_MULTILANG is not set	<remove the line>
GATEWAY_BEYOND_SUBNET_SUPPORT=1
CONFIG_GATEWAY_BEYOND_SUBNET=y
# DEBUG_GATEWAY_BEYOND_SUBNET is not set	<remove the line>
#VPN_SUPPORT	is not set     <remove the line>
# CONFIG_VPN is not set	<remove the line>
#DHCP_DOMAIN_IP_MAPPING_SUPPORT	is not set     <remove the line>
# CONFIG_DHCP_DOMAIN_IP_MAPPING is not set	<remove the line>

CY_DEPS := $(SRCBASE)/include/code_pattern.h $(SRCBASE)/include/cyutils.h $(SRCBASE)/include/cymac.h $(SRCBASE)/cy_conf.h $(SRCBASE)/cy_conf.mak Makefile $(shell find -iname "*.h")
