// Automatically generated by gen.pl, don't edit #	<remove the line>

//#define	MULTIPVC_SUPPORT	0	<remove the line>
//#define	CONFIG_MULTIPVC	n	<remove the line>
//#define	AUTODETECT_DHCP_SUPPORT	0	<remove the line>
//#define	CONFIG_AUTODETECT_DHCP	n	<remove the line>
//#define	SNMPV3_SUPPORT	0	<remove the line>
//#define	CONFIG_SNMPV3	n	<remove the line>
//#define	QOS_ADVANCE_SUPPORT	0	<remove the line>
//#define	CONFIG_QOS_ADVANCE	n	<remove the line>
//#define	SAVE_LOG_SUPPORT	0	<remove the line>
//#define	CONFIG_SAVE_LOG	n	<remove the line>
//#define	ADVANCED_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_ADVANCED_FORWARD	n	<remove the line>
//#define	DNSPROXY_BUTTON_SUPPORT	0	<remove the line>
//#define	CONFIG_DNSPROXY_BUTTON	n	<remove the line>
//#define	NOMAD_SUPPORT	0	<remove the line>
//#define	CONFIG_NOMAD	n	<remove the line>
#define	QOS_SUPPORT	1
#define	CONFIG_QOS	y
//#define	QOS_ADVANCED_SUPPORT	0	<remove the line>
//#define	CONFIG_QOS_ADVANCED	n	<remove the line>
//#define	ROUTED_UNLIMIT_SUPPORT	0	<remove the line>
//#define	CONFIG_ROUTED_UNLIMIT	n	<remove the line>
//#define	CLI_SUPPORT	0	<remove the line>
//#define	CONFIG_CLI	n	<remove the line>
//#define	IPCP_NETMASK_SUPPORT	0	<remove the line>
//#define	CONFIG_IPCP_NETMASK	n	<remove the line>
//#define	SETUP_WIZARD_FT_SUPPORT	0	<remove the line>
//#define	CONFIG_SETUP_WIZARD_FT	n	<remove the line>
//#define	SECLAN_SUPPORT	0	<remove the line>
//#define	CONFIG_SECLAN	n	<remove the line>
#define	DSL_MODULA_SEL_SUPPORT	1
#define	CONFIG_DSL_MODULA_SEL	y
//#define	LOG_DSL_MODULA_SEL	0 	<remove the line>
//#define	CPED_TR064_SUPPORT	0	<remove the line>
//#define	CONFIG_CPED_TR064	n	<remove the line>
//#define	STB_SUPPORT	0	<remove the line>
//#define	CONFIG_STB	n	<remove the line>
#define	DNSMASQ_SUPPORT	1
#define	CONFIG_DNSMASQ	y
//#define	LOG_DNSMASQ	0 	<remove the line>
#define	UDHCPD_SUPPORT	1
#define	CONFIG_UDHCPD	y
#define	UDHCPC_SUPPORT	1
#define	CONFIG_UDHCPC	y
//#define	LOG_DHCPD	0 	<remove the line>
//#define	LOG_DHCPC	0 	<remove the line>
#define	IGMP_PROXY_SUPPORT	1
#define	CONFIG_IGMP_PROXY	y
//#define	GRE_SUPPORT	0	<remove the line>
//#define	CONFIG_GRE	n	<remove the line>
//#define	CLOUD_SUPPORT	0	<remove the line>
//#define	CONFIG_CLOUD	n	<remove the line>
//#define	IP2_IP_SUPPORT	0	<remove the line>
//#define	CONFIG_IP2_IP	n	<remove the line>
//#define	FILTER_WAN_SELECT_SUPPORT	0	<remove the line>
//#define	CONFIG_FILTER_WAN_SELECT	n	<remove the line>
#define	PPPOE_SUPPORT	1
#define	CONFIG_PPPOE	y
//#define	LOG_PPPOE	0 	<remove the line>
//#define	PPTP_SUPPORT	0	<remove the line>
//#define	CONFIG_PPTP	n	<remove the line>
//#define	LOG_PPTP	0 	<remove the line>
#define	PPPD_SUPPORT	1
#define	CONFIG_PPPD	y
//#define	LOG_PPPD	0 	<remove the line>
#define	ZEBRA_SUPPORT	1
#define	CONFIG_ZEBRA	y
//#define	LOG_ZEBRA	0 	<remove the line>
#define	TFTPD_SUPPORT	1
#define	CONFIG_TFTPD	y
//#define	LOG_TFTPD	0 	<remove the line>
#define	DDNS_SUPPORT	1
#define	CONFIG_DDNS	y
//#define	LOG_DDNS	0 	<remove the line>
#define	CRON_SUPPORT	1
#define	CONFIG_CRON	y
//#define	LOG_CRON	0 	<remove the line>
#define	HTTPD_SUPPORT	1
#define	CONFIG_HTTPD	y
#define	GET_POST_SUPPORT	1
#define	CONFIG_GET_POST	y
//#define	LOG_HTTPD	0 	<remove the line>
//#define	CWMP_SUPPORT	0	<remove the line>
//#define	CONFIG_CWMP	n	<remove the line>
//#define	LOG_CWMP	0 	<remove the line>
#define	ANTSEL_SUPPORT	1
#define	CONFIG_ANTSEL	y
//#define	LOG_ANTSEL	0 	<remove the line>
//#define	WL_CALIBRATION_ONBOARD_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_CALIBRATION_ONBOARD	n	<remove the line>
//#define	LOG_WL_CALIBRATION_ONBOARD	0 	<remove the line>
#define	LIBMNG_SUPPORT	1
#define	CONFIG_LIBMNG	y
//#define	LOG_LIBMNG	0 	<remove the line>

#if 1
//#define	HSIAB_SUPPORT	0	<remove the line>
//#define	CONFIG_HSIAB	n	<remove the line>
//#define	LOG_HSIAB	0 	<remove the line>
//#define	HEARTBEAT_SUPPORT	0	<remove the line>
//#define	CONFIG_HEARTBEAT	n	<remove the line>
//#define	LOG_HEARTBEAT	0 	<remove the line>
//#define	AOL_SUPPORT	0	<remove the line>
//#define	CONFIG_AOL	n	<remove the line>
#define	SETUP_WIZARD_SUPPORT	1
#define	CONFIG_SETUP_WIZARD	y
//#define	PARENTAL_CONTROL_SUPPORT	0	<remove the line>
//#define	CONFIG_PARENTAL_CONTROL	n	<remove the line>
//#define	LOG_PARENTAL_CONTROL	0 	<remove the line>
//#define	DDM_SUPPORT	0	<remove the line>
//#define	CONFIG_DDM	n	<remove the line>
//#define	LOG_DDM	0 	<remove the line>
#define	NTP_SUPPORT	1
#define	CONFIG_NTP	y
#define	MPPPOE_SUPPORT	1
#define	CONFIG_MPPPOE	y
#define	IPPPOE_SUPPORT	1
#define	CONFIG_IPPPOE	y
//#define	CLIP_SUPPORT	0	<remove the line>
//#define	CONFIG_CLIP	n	<remove the line>
//#define	HTTPS_SUPPORT	0	<remove the line>
//#define	CONFIG_HTTPS	n	<remove the line>
//#define	ARP_TABLE_SUPPORT	0	<remove the line>
//#define	CONFIG_ARP_TABLE	n	<remove the line>
//#define	SPECIAL_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_SPECIAL_FORWARD	n	<remove the line>
#define	BACKUP_RESTORE_SUPPORT	1
#define	CONFIG_BACKUP_RESTORE	y

#if 0
//#define	FIREWALL_LEVEL_SUPPORT	0	<remove the line>
//#define	CONFIG_FIREWALL_LEVEL	n	<remove the line>
#endif

#define	UPNP_FORWARD_SUPPORT	1
#define	CONFIG_UPNP_FORWARD	y
#define	PORT_TRIGGER_SUPPORT	1
#define	CONFIG_PORT_TRIGGER	y
#define	WRITE_MAC_SUPPORT	1
#define	CONFIG_WRITE_MAC	y
#define	WRITE_SN_SUPPORT	1
#define	CONFIG_WRITE_SN	y
#define	DIAG_SUPPORT	1
#define	CONFIG_DIAG	y
#endif

//#define	MULTIUSER_SUPPORT	0	<remove the line>
//#define	CONFIG_MULTIUSER	n	<remove the line>
#define	SINGLEUSER_SUPPORT	1
#define	CONFIG_SINGLEUSER	y
//#define	RIP_EXTEND_SUPPORT	0	<remove the line>
//#define	CONFIG_RIP_EXTEND	n	<remove the line>

#if 0
//#define	WL_STA_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_STA	n	<remove the line>
#endif

//#define	SYSLOG_SUPPORT	0	<remove the line>
//#define	CONFIG_SYSLOG	n	<remove the line>
//#define	KLOGD_SUPPORT	0	<remove the line>
//#define	CONFIG_KLOGD	n	<remove the line>
//#define	SNMP_SUPPORT	0	<remove the line>
//#define	CONFIG_SNMP	n	<remove the line>
//#define	LOG_SNMP	0 	<remove the line>
//#define	NETMASK_CLASS_SUPPORT	0	<remove the line>
//#define	CONFIG_NETMASK_CLASS	n	<remove the line>
//#define	PPP_DETAIL_STAT_SUPPORT	0	<remove the line>
//#define	CONFIG_PPP_DETAIL_STAT	n	<remove the line>
//#define	EMI_TEST	0 	<remove the line>
//#define	DEBUG_WEB	0 	<remove the line>
//#define	DEBUG_RC	0 	<remove the line>
//#define	BRCM	0 	<remove the line>
//#define	MY_DEBUG	0 	<remove the line>
#define	MULTILANG_SUPPORT	1
#define	CONFIG_MULTILANG	y
//#define	DEBUG_MULTILANG	0 	<remove the line>
#define	GATEWAY_BEYOND_SUBNET_SUPPORT	1
#define	CONFIG_GATEWAY_BEYOND_SUBNET	y
//#define	DEBUG_GATEWAY_BEYOND_SUBNET	0 	<remove the line>
//#define	VPN_SUPPORT	0	<remove the line>
//#define	CONFIG_VPN	n	<remove the line>
//#define	DHCP_DOMAIN_IP_MAPPING_SUPPORT	0	<remove the line>
//#define	CONFIG_DHCP_DOMAIN_IP_MAPPING	n	<remove the line>
