#!/bin/bash
#
# RCSID $Id: ttn,v 1.1.1.2 2005/03/28 06:57:41 sparq Exp $
#
# This script is OBSOLETE -- rgb, May 6th, 1998
set +v
insmod ipsec.o
tncfg attach ipsec0 eth2
ifconfig ipsec0 10.2.0.143 up netmask 255.255.0.0
route del 10.2.0.0
route add -net 10.2.0.0 netmask 255.255.0.0 dev ipsec0


#
# $Log: ttn,v $
# Revision 1.1.1.2  2005/03/28 06:57:41  sparq
# - GuangZhou release v1.00.57
#
# Revision 1.1.1.1  2004/07/26 01:39:25  sparq
# Mirror v0.01.9 release from K.C division of CyberTAN.
#
# Revision 1.1.1.1  2002/09/05 03:13:18  ken
# 1.98b
#
# Revision 1.3  1999/04/06 04:54:36  rgb
# Fix/Add RCSID Id: and Log: bits to make PHMDs happy.  This includes
# patch shell fixes.
#
#
