#  Copyright 2001, Cybertan Corporation
#  All Rights Reserved.
#  
#  This is UNPUBLISHED PROPRIETARY SOURCE CODE of Cybertan Corporation;
#  the contents of this file may not be disclosed to third parties, copied or
#  duplicated in any form, in whole or in part, without the prior written
#  permission of Cybertan Corporation.
#
#
# $Id: Makefile,v 1.1.1.2 2005/03/28 06:56:14 sparq Exp $
#

O_TARGET	:= writemac.o

export-objs	:= 

include $(TOPDIR)/Rules.make

