# $Id: Makefile,v 1.1.1.2 2005/03/28 06:56:08 sparq Exp $
# Makefile for Maple Bus drivers

O_TARGET	:= maplebus.o

export-objs	:= maple.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_MAPLE)		+= maple.o

include $(TOPDIR)/Rules.make
