# File: drivers/atm/ti_evm3/Makefile
#
# Makefile for the Texas Instruments EVM3 ADSL/ATM driver.
#
#
# Copyright (c) 2000 Texas Instruments Incorporated.
# 	Jeff Harrell (jharrell@telogy.com)
# 	Viren Balar  (vbalar@ti.com)
# 	Victor Wells (vwells@telogy.com)
#
include $(TOPDIR)/Rules.make







