#
# Makefile for common code for the NEC VR41xx family
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#

O_TARGET:= vr41xx.o

obj-y	 := reset.o cmu.o

include $(TOPDIR)/Rules.make
