//Automatically generated by gen_codepattern, don't edit

#ifndef CY_CODEPATTERN_H
#define CY_CODEPATTERN_H

#define	MonitorMajorRev	0
#define	MonitorMinorRev	22
#define	TelogyMonitorRev	6
#define	MonitorMajorRev_PSBL	0
#define	MonitorMinorRev_PSBL	22
#define	TelogyMonitorRev_PSBL	19
#define	IncRev	TelogyMonitorRev_PSBL
#define	BuildNum	5
#define	ADSL_TYPE	AnnexA
#define	CODE_TYPE	COMMON
#define	PROJECT	WAG354G
#define	CUSTOMER	VZ
#define	LOCALE	EUROPE
#define	RELCOUN	EUROPE
#define	COUNTRY	LOCALE
#define	FLASHTYPE	AMD
#define	FLASH_SIZE	4
#define	DRAM_SIZE	16
#define	BOOT_SIZE	128
#define	WEB_PAGE	wag354gm

#endif
