MOD_CRYPTOAPI := ipsec_cryptoapi.o

ALG_MODULES += $(MOD_CRYPTOAPI)

obj-$(CONFIG_IPSEC_ALG_CRYPTOAPI) += $(MOD_CRYPTOAPI)
static_init-func-$(CONFIG_IPSEC_ALG_CRYPTOAPI)+= ipsec_cryptoapi_init
alg_obj-$(CONFIG_IPSEC_ALG_CRYPTOAPI) += ipsec_alg_cryptoapi.o

CRYPTOAPI_OBJS := ipsec_alg_cryptoapi.o 
$(MOD_CRYPTOAPI): $(CRYPTOAPI_OBJS)
	$(LD) -r $(CRYPTOAPI_OBJS) -o $@
