OUTPUT_FORMAT("elf32-littlemips")
OUTPUT_ARCH(mips)
ENTRY(tikernelunzip)
SECTIONS
{

   /* Allocate bss space on top of kernel bss space */
        . = _fbss;
        bss :
        {
               inflate_bss_start = .;
                *(.dynbss)
                *(.bss)
                *(COMMON)
                *(.sbss)
                *(.scommon)
               inflate_bss_end = .;
                . = ALIGN (0x8000);
               inflate_slide_window = .;
                . += 0x8000;  /* slide window is 8000h */
               inflate_free_memory_start = .;
        }


   /* Allocate text and data in flash just above file system */
/*        .text 0x9c500000 : /* Atlas */
/*        .text 0x90400000 : */ /* Sead */
	  .text 0x90570000 : /* Sead */
        {
                *(.text)
                *(.rodata)
                *(.rodata1)
                *(.gnu.warning)
                *(.text.init)
                *(.data.init)
        }                    
        
        .data :
        {
                *(*)
        }

}














