/* Object identifiers (OIDs) used by FreeS/WAN
 * Copyright (C) 2003 Andreas Steffen, Zuercher Hochschule Winterthur
 * 
 * This file has been automatically generated by the script oid.pl
 * Do not edit manually!
 */

typedef struct {
    u_char octet;
    u_int  next;
    u_int  down;
    const u_char *name;
} oid_t;

extern const oid_t oid_names[];

#define OID_SUBJECT_ALT_NAME		31
#define OID_BASIC_CONSTRAINTS		33
#define OID_CRL_DISTRIBUTION_POINTS	35
#define OID_RSA_ENCRYPTION		47
#define OID_MD2_WITH_RSA		48
#define OID_MD5_WITH_RSA		49
#define OID_SHA1_WITH_RSA		50
#define OID_SHA256_WITH_RSA		51
#define OID_SHA384_WITH_RSA		52
#define OID_SHA512_WITH_RSA		53
#define OID_PKCS7_DATA			55
#define OID_PKCS7_SIGNED_DATA		56
#define OID_PKCS9_EMAIL			62
#define OID_MD2				65
#define OID_MD5				66
#define OID_SHA1			82
