ALG:=1des
CONFIG_YES:=$(CONFIG_IKE_ALG_1DES)
DIR_1DES:=$(LIBCRYPTO)/../libdes

ALG_DIRS-$(CONFIG_YES) := $(ALG_DIRS-$(CONFIG_YES)) $(DIR_1DES)
## libdes.a already in pluto for 3DES: $(DIR_1DES)/libdes.a
ALG_LIBS-$(CONFIG_YES) := $(ALG_LIBS-$(CONFIG_YES))  
ALG_SRCS-$(CONFIG_YES) := $(ALG_SRCS-$(CONFIG_YES)) ike_alg_$(ALG).c
ALG_OBJS-$(CONFIG_YES) := $(ALG_OBJS-$(CONFIG_YES)) ike_alg_$(ALG).o

$(DIR_1DES)/libdes.a:
	make -C $(DIR_1DES) CFLAGS="$(CFLAGS)" libdes.a

ike_alg_$(ALG).o: ike_alg_$(ALG).c
	$(CC) -I $(LIBCRYPTO)/.. $(COPTS) $(ALLFLAGS) -c $<
